version: '3.8'

name: ecommerce

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file: .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - networkEcommerce
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

  nextjs:
    container_name: nextjs
    networks:
      - networkEcommerce
    build:
      target: production
      context: .
      args:
        - PORT="3000"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

networks:
  networkEcommerce:
    name: networkEcommerce
    driver: bridge

volumes:
  node_modules:
  mysql: