apiVersion: apps/v1
kind: Deployment
metadata:
  name: gecommerceadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gecommerceadmin
  template:
    metadata:
      labels:
        app: gecommerceadmin
    spec:
      containers:
        - name: gecommerceadmin
          image: crecommerceauto.azurecr.io/gecommerceadmin
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              value: "pk_test_c2hhcmluZy1iYXQtODYuY2xlcmsuYWNjb3VudHMuZGV2JA"
            - name: CLERK_SECRET_KEY
              value: "sk_test_C0fELViaM3qD3u3w2OII46AezBx5p4JcXPmj88eKfD"
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              value: "/sign-in"
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              value: "/sign-up"
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              value: "/"
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              value: "/"
            - name: DATABASE_URL
              value: "mysql://mysqladmin:H@Sh1CoR3!@ecommerce-autoiac-mysqlserver.mysql.database.azure.com:3306/app"
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              value: "dbjrujkcg"
            - name: STRIPE_API_KEY
              value: "sk_test_51P8pSCJ1AaM8kFGZYUQ7xqojng2gQmKnzIXXe55nevsMYKvFD41PTiSyaSoydnMsLarwvh4o71yoUebKNpFmFcxX00XmwBz033"
            - name: FRONTEND_STORE_URL
              value: "http://ecommerce:3001"
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_f3d41e2a427dee4932f5cb254f17061d9e0c8e5af008defe198ca35a37413028"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "app"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "root"
