apiVersion: v1
kind: Service
metadata:
  name: gecommerceadmin
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: gecommerceadmin
